const express=require('express');
const Router=express.Router();
const {Signin,Signup,Logout,GetAllApplication,SetStatus,GetAllApproved,GetAllRejected} = require('../controllers/Admin.controller');
Router.post('/auth/signup',Signup);
Router.post('/auth/signin',Signin);
Router.get('/auth/logout',Logout);
Router.get('/application/getAll',GetAllApplication);
Router.post('/setStatus/:id',SetStatus);
Router.get('/application/getAllApproved',GetAllApproved);
Router.get('/application/getAllRejected',GetAllRejected);
module.exports=Router;